[project]
requires-python = ">=3.11"
name = "Vit_Pytorch"
version = "0.1.0"
description = "Implement from scratch a Dynamic Vision Transformer"
dependencies = [
    "numpy",
    "tqdm",
    "torch",
    "torchinfo",
    "torchvision",
    "matplotlib",
    "tensorboard",
    "seaborn",
    "scikit-learn",
    "datasets[vision]",
    "pytest",
    "black",
    "pylint",
    "dotenv>=0.9.9",
]

[dependency-groups]
dev = [
  "pytest",
  "black",
  "isort",
  "pylint",
  "calflops",
  "transformers"
]


[scripts]
test = "pytest"
format = "black . && isort ."
lint = "pylint app"
