[project]
name = "Vit_Pytorch"
version = "0.1.0"
description = "Mise en place d'un Vision transformer"
dependencies = [
    "numpy",
    "tqdm",
    "torch",
    "torchinfo",
    "torchvision",
    "matplotlib",
    "Pillow",
    "tensorboard",
    "seaborn",
    "scikit-learn",
    "datasets[vision]",
    "pytest",
    "black",
    "pylint",
    "omegaconf",
    "hydra"
]

[dependency-groups]
dev = [
  "pytest",
  "black",
  "isort",
  "pylint"
]


[scripts]
test = "pytest"
format = "black . && isort ."
lint = "pylint app"
